X:
  kernel: 
    type: "linear"
    lower_bound: 0
    upper_bound: 1
    sample_domain: [0, 1]
    terms:
      - intercept: 0
        indicators: null
        value: -1
        variables:
          1: ["A"]
  dependencies:
    1: ["A"]
A:
  kernel:
    type: "uniform"
    sample_domain: [-1, 1]
    prob: [0.8, 0.2]
    terms: null
  dependencies: null
R:
  kernel: 
    type: "linear"
    lower_bound: 0
    upper_bound: 1.1
    noise: 0.4
    sample_domain: [0.0, 0.1, 0.9, 1.1]
    terms:
      - intercept: 0
        indicators: null
        value: 0.1
        variables:
          1: ["A"]
      - intercept: 0
        indicators: null
        value: 1
        variables:
          1: ["X"]
  dependencies:
    1: ["A", "X"]
