U1:
  kernel:
    type: "uniform"
    sample_domain: [0, 1]
    probs: [0.8, 0.2]
    terms: null
  dependencies: null
U2:
  kernel:
    type: "uniform"
    sample_domain: [0, 1]
    probs: [0.8, 0.2]
    terms: null
  dependencies: null
C:
  kernel:
    type: "linear"
    sample_domain: [-1, 0, 1]
    lower_bound: -1
    upper_bound: 1
    noise: 0.2
    terms:
      - intercept: 0
        indicators: null
        value: -1
        variables:
          0: ["U1"]
      - intercept: 0
        indicators: null
        value: 1
        variables:
          0: ["U2"]
  dependencies:
    0: ["U1", "U2"]
A:
  kernel:
    type: "linear"
    noise: 0.2
    sample_domain: [1, 2, 3]
    lower_bound: 1
    upper_bound: 2
    terms:
      - intercept: 1
        indicators:
          - type: "greater_than_value"
            variable:
              0: "X"
            threshold: 0
          - type: "greater_or_equal_than_value"
            variable:
              1: "A"
            threshold: 1
        variables: null
      - intercept: 2
        indicators: null
        value: -1
        variables:
          0: ["U1"]
  dependencies:
    0: ["X", "U1"]
    1: ["A"]
  level_offset: 0.1
X:
  kernel:
    type: "linear"
    noise: 0.2
    sample_domain: [0, 1]
    lower_bound: 0
    upper_bound: 1
    terms:
      - intercept: 0
        indicators: null
        value: 1
        variables:
          1: ["U2"]
  dependencies:
    1: ["U2"]
R:
  kernel: 
    type: "linear"
    sample_domain: [0, 1, 2, 3]
    lower_bound: 0
    upper_bound: 2
    terms:
      - intercept: 0
        indicators: null
        value: 1
        variables:
          0: ["X"]
          1: ["A"]
  dependencies:
    0: ["X"]
    1: ["A"]
  level_offset: 0
