U:
  kernel: 
    type: "uniform"
    sample_domain: [-1, 1]
    terms: null
  dependencies: null
X:
  kernel:
    type: "linear"
    noise: 0.2
    sample_domain: [-1.1, 0.0, 1.1, 2.9]
    lower_bound: -1.1
    upper_bound: 2.9
    terms:
      - intercept: 1
        indicators: null
        value: -1
        variables:
          1: ["U"]
      - intercept: 0
        indicators: null
        value: 1
        variables:
          1: ["A", "U"]
      - intercept: 0
        indicators: null
        value: 0.1
        variables:
          1: ["A"]
  dependencies:
    1: ["A", "U"]
A:
  kernel:
    type: "linear"
    noise: 0.2
    sample_domain: [-1, 1]
    lower_bound: -1
    upper_bound: 1
    terms:
      - intercept: 0
        indicators: null
        value: 1
        variables:
          0: ["U"]
  dependencies:
    0: ["U"]
  level_offset: 0.1
R:
  kernel: 
    type: "binomial"
    sample_domain: [0, 1]
    dim: 2
    terms:
      - intercept: 0
        indicators: null
        value: 0.1
        variables:
          1: ["A"]
      - intercept: 0
        indicators: null
        value: 1
        variables:
          1: ["X"]
  dependencies:
    1: ["A", "X"]
  level_offset: 0
