U:
  kernel:
    type: "uniform"
    sample_domain: [1, 2, 3]
    terms: null
  dependencies: null
D:
  kernel:
    type: "linear"
    sample_domain: [0, 1]
    lower_bound: 0
    upper_bound: 1
    noise: 0.10 # 1. Markov parameter.
    terms:
      - intercept: 0
        value: 1
        indicators: null
        variables:
          1: ["D"]
  dependencies:
    1: ["D"]
DE:
  kernel:
    type: "linear"
    sample_domain: [0, 1]
    lower_bound: 0
    upper_bound: 1
    noise: 0.25
    terms:
      - intercept: 0
        value: 1
        indicators: null
        variables:
          0: ["D"]
  dependencies:
    0: ["D"]
L1:
  kernel:
    type: "poisson"
    limit:
      value: 6
      variables: null
    noise: 0.15
    terms:
      - intercept: 0 # 3. Confounding
        value: 0
        indicators:
          - type: "greater_than_variable"
            variable:
              1: "U"
            threshold:
              1: "A1"
        variables: null
      - intercept: 1
        value: -0.65
        indicators: null
        variables:
          1: ["A1", "A1"]
      - intercept: 0
        value: 0.5
        indicators: null
        variables:
          1: ["A1", "A1", "D"]
  dependencies:
    1: ["D", "A1", "U"]
    2: ["A2"]
L2:
  kernel:
    type: "poisson"
    limit:
      value: 6
      variables:
        1: ["L1"]
    noise: 0.15
    terms:
      - intercept: 0 # 2. Dyn. back-door param.
        value: 0
        indicators:
          - type: "greater_than_variable"
            variable:
              2: "A2"
            threshold:
              1: "A2"
        variables: null
      - intercept: 1
        value: -0.65
        indicators: null
        variables:
          1: ["A2", "A2"]
      - intercept: 0
        value: 0.2
        indicators: null
        variables:
          1: ["A2", "A2"]
          2: ["D"]
  dependencies:
    1: ["L1", "A2"]
    2: ["D", "A2"]
R:
  kernel:
    type: "linear"
    sample_domain: [0]
    lower_bound: 0
    upper_bound: 1000
    terms:
      - intercept: 0
        value: 1
        indicators: null
        variables:
          1: ["A1"]
          0: ["L1"]
      - intercept: 0
        value: 1
        indicators: null
        variables:
          1: ["A2"]
          0: ["L2"]
  dependencies:
    0: ["L1", "L2"]
    1: ["A1", "A2"]
A1:
  kernel:
    type: "mixed"
    noise: 0.15
    mixed_probs: [1, 0] # 3. Confounding parameter.
    sample_domain: [1, 2, 3]
    kernels:
      - type: "linear"
        sample_domain: [1, 2, 3]
        lower_bound: 1
        upper_bound: 3
        terms:
          - intercept: 1
            value: 0
            indicators:
              - type: "greater_than_value"
                variable:
                  0: "L1"
                threshold: 0
              - type: "greater_or_equal_than_value"
                variable:
                  1: "A1"
                threshold: 2
            variables: null
          - intercept: 1
            value: 1
            indicators: null
            variables:
              0: ["DE"]
      - type: "linear"
        sample_domain: [1, 2, 3]
        lower_bound: 1
        upper_bound: 3
        terms:
          - intercept: -1
            value: 1
            indicators: null
            variables:
              0: ["U"]
  dependencies:
    0: ["DE", "L1", "U"]
    1: ["A1"]
A2:
  kernel:
    type: "linear"
    sample_domain: [1, 2, 3]
    lower_bound: 1
    upper_bound: 3
    noise: 0.15
    terms:
      - intercept: 0
        value: 1
        indicators:
          - type: "greater_than_value"
            variable:
              0: "L1"
            threshold: 0
          - type: "greater_or_equal_than_value"
            variable:
              1: "A1"
            threshold: 2
        variables:
          1: ["A1"]
      - intercept: 1
        value: 0 # 2. Dyn. back-door param.
        indicators: null
        variables:
          1: ["A2"]
  dependencies:
    0: ["L1"]
    1: ["A1", "A2"]
