state:
  1: ["DE", "L1"]
  2: ["DE", "A1"]
action:
  1: ["A1", "A2"]
reward:
  0: ["R"]
variables:
  U1:
    kernel:
      type: "uniform"
      domain: [1, 2, 3]
      terms: null
    dependencies: null
    level_offset: 0
  D:
    kernel:
      type: "linear"
      sample_domain: [0, 1]
      noise:
        type: "random"
        prob: 1 # 1. Markov parameter
      intercept: 0
      terms:
        - param: 1
          variables:
            1: ["D"]
    dependencies:
      1: ["D"]
    level_offset: 0
  DE:
    kernel:
      type: "linear"
      sample_domain: [0, 1]
      noise:
        type: "random"
        prob: 0.25
      terms:
        - param: 1
          variables:
            0: ["D"]
    dependencies:
      0: ["D"]
    level_offset: 0
  L1:
    kernel:
      type: "poisson"
      limit:
        value: 6
        variables: null
      noise:
        type: "random"
        prob: 0.15
      indicator_terms:
        - type: "greater_than_variable"
          variable:
            1: ["U1"]
          threshold:
            1: ["A1"]
          intercept: 1 # 3. Confounding parameter.
          terms: null
      intercept: 1
      terms:
        - param: -0.65
          variables:
            1: ["A1", "A1"]
        - param: 0.5
          variables:
            1: ["A1", "A1", "D"]
    dependencies:
      1: ["D", "A1", "U1"]
      2: ["A2"]
    level_offset: 0
  L2:
    kernel:
      type: "poisson"
      limit:
        value: 6
        variables:
          1: ["L1"]
      noise:
        type: "random"
        prob: 0.15
      indicator_terms:
        - type: "greater_than_variable"
          variable:
            1: ["A2"]
          threshold:
            2: ["A2"]
          intercept: 0 # 2. Dyn. Back-door parameter
          terms: null
      intercept: 1
      terms:
        - param: -0.65
          variables:
            1: ["A2", "A2"]
        - param: 0.2
          variables:
            1: ["A2", "A2"]
            2: ["D"]
    dependencies:
      1: ["L1", "A2"]
      2: ["D", "A2"]
    level_offset: 0
  R:
    kernel:
      type: "linear"
      sample_domain: [0]
      lower_bound: 0
      noise:
        type: "random"
        prob: 0.15
      terms:
        - param: 1
          variables:
            1: ["A1"]
            0: ["L1"]
        - param: 1
          variables:
            1: ["A2"]
            0: ["L2"]
    dependencies:
      0: ["L1", "L2"]
      1: ["A1", "A2"]
    level_offset: 0
  A1:
    kernel:
      type: "mixed"
      noise:
        type: "random"
        prob: 0.15
      mixed_probs: [0.9, 0.1] # 3. Confounding parameter.
      kernels:
        - type: "linear"
          sample_domain: [1, 2, 3]
          lower_bound: 1
          upper_bound: 3
          indicator_terms:
            - type: "multiple"
              indicators:
                - type: "greater_than_value"
                  variable:
                    0: ["L1"]
                  threshold: 0
                - type: "greater_or_equal_than_value"
                  variable:
                    1: ["A1"]
                  threshold: 2
              intercept: 1
              terms: null
          intercept: 1
          terms:
            - param: 1
              variables:
                0: ["DE"]
        - type: "linear"
          sample_domain: [1, 2, 3]
          lower_bound: 1
          upper_bound: 3
          intercept: -1
          terms:
            - param: 1
              variables:
                0: ["U1"]
    dependencies:
      0: ["DE", "L1", "U1"]
      1: ["A1"]
    level_offset: 0.1
  A2:
    kernel:
      type: "linear"
      sample_domain: [1, 2, 3]
      lower_bound: 1
      upper_bound: 3
      noise:
        type: "random"
        prob: 0.15
      indicator_terms:
        - type: "multiple"
          indicators:
            - type: "greater_than_value"
              variable:
                0: ["L1"]
              threshold: 0
            - type: "greater_or_equal_than_value"
              variable:
                1: ["A1"]
              threshold: 2
          intercept: 0
          terms:
            - param: 1
              variables:
                1: ["A1"]
      intercept: 1
      terms:
        - param: 0 # 2. Dyn. Back-door parameter
          variables:
            1: ["A2"]
    dependencies:
      0: ["L1"]
      1: ["A1", "A2"]
    level_offset: 0.1
