example_1:
  state: null
  action: 
    1: ["A"]
  reward: 
    0: ["R"]
example_2:
  state: null
  correct_state: 
    2: ["A"]
  action: 
    1: ["A"]
  reward: 
    0: ["R"]
example_3:
  state: 
    1: ["C"]
  correct_state: null
  action:
    1: ["A"]
  reward: 
    0: ["R"]
pricing_specs:
  state:
    1: ["DE", "L1"]
    2: ["DE", "A1"]
  correct_state:
    1: ["DE", "L1"]
    2: ["DE", "A1"]
  action:
    1: ["A1", "A2"]
  reward:
    0: ["R"]
pricing_no_markov:
  state:
    1: ["DE", "L1"]
    2: ["DE", "A1"]
  action:
    1: ["A1", "A2"]
  reward:
    0: ["R"]
pricing_dyn_back_door:
  state:
    1: ["DE", "L1"]
    2: ["DE", "A1"]
  correct_state:
    1: ["DE", "L1"]
    2: ["DE", "A1", "A2"]
  action:
    1: ["A1", "A2"]
  reward:
    0: ["R"]
pricing_confounded:
  state:
    1: ["DE", "L1"]
    2: ["DE", "A1"]
  action:
    1: ["A1", "A2"]
  reward:
    0: ["R"]
